### ISSUE TITLE
Program error

### ISSUE THREAD

**Issue by hariharen9** [rajatkeshri/Flood-prediction#2]
![image](https://user-images.githubusercontent.com/57080243/105720369-5f3cbf00-5f49-11eb-9583-448dddd6f064.png)
I get this error

**Comment by shahinashaji** [comment]
Use iloc instead of ix. Because it's deprecated. Use like this - x.iloc[:,[16,20,21]].

**Comment by Shweta200126** [comment]
> Use iloc instead of ix. Because it's deprecated. Use like this - x.iloc[:,[16,20,21]].

This helped, thank you.
